[package]
name = "proto_hackers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.86"
fancy-regex = "0.14.0"
serde_json = "1.0.139"
tokio = {version =  "1.43.0", features = ["full"]}
