[package]
name = "proto_hackers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
serde_json = "1.0.139"
tokio = {version =  "1.43.0", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync"]}
